=== druyaned/active-recorder/src/main/java/com/github/druyaned/active_recorder/data_files/config.dtd
<!ELEMENT activeTimes (item+)>
<!ELEMENT item (start, stop, mode, descr)>
<!ELEMENT start (year, month, day, hour, minute, second)>
<!ELEMENT stop (year, month, day, hour, minute, second)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT hour (#PCDATA)>
<!ELEMENT minute (#PCDATA)>
<!ELEMENT second (#PCDATA)>
<!ELEMENT mode (#PCDATA)>
<!ELEMENT descr (#PCDATA)>

=== druyaned/active-recorder/src/main/java/com/github/druyaned/active_recorder/data_files/data.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE activeTimes SYSTEM "config.dtd">
<activeTimes>
  <item>
    <start>
      <year>2020</year>
      <month>4</month>
      <day>29</day>
      <hour>10</hour>
      <minute>17</minute>
      <second>31</second>
    </start>
    <stop>
      <year>2020</year>
      <month>4</month>
      <day>29</day>
      <hour>13</hour>
      <minute>17</minute>
      <second>31</second>
    </stop>
    <mode>RELAXATION</mode>
    <descr>none0</descr>
  </item>
  <item>
    <start>
      <year>2021</year>
      <month>4</month>
      <day>1</day>
      <hour>13</hour>
      <minute>29</minute>
      <second>23</second>
    </start>
    <stop>
      <year>2021</year>
      <month>4</month>
      <day>1</day>
      <hour>16</hour>
      <minute>22</minute>
      <second>42</second>
    </stop>
    <mode>STAGNATION</mode>
    <descr>none1</descr>
  </item>
  <item>
    <start>
      <year>2021</year>
      <month>8</month>
      <day>2</day>
      <hour>10</hour>
      <minute>17</minute>
      <second>31</second>
    </start>
    <stop>
      <year>2021</year>
      <month>8</month>
      <day>2</day>
      <hour>13</hour>
      <minute>17</minute>
      <second>31</second>
    </stop>
    <mode>DEVELOPMENT</mode>
    <descr>none2</descr>
  </item>
  <item>
    <start>
      <year>2021</year>
      <month>8</month>
      <day>3</day>
      <hour>23</hour>
      <minute>59</minute>
      <second>59</second>
    </start>
    <stop>
      <year>2021</year>
      <month>8</month>
      <day>4</day>
      <hour>0</hour>
      <minute>0</minute>
      <second>0</second>
    </stop>
    <mode>DEVELOPMENT</mode>
    <descr>none3</descr>
  </item>
  <item>
    <start>
      <year>2021</year>
      <month>8</month>
      <day>4</day>
      <hour>0</hour>
      <minute>0</minute>
      <second>0</second>
    </start>
    <stop>
      <year>2021</year>
      <month>8</month>
      <day>4</day>
      <hour>2</hour>
      <minute>53</minute>
      <second>18</second>
    </stop>
    <mode>DEVELOPMENT</mode>
    <descr>none3</descr>
  </item>
  <item>
    <start>
      <year>2021</year>
      <month>9</month>
      <day>4</day>
      <hour>23</hour>
      <minute>59</minute>
      <second>59</second>
    </start>
    <stop>
      <year>2021</year>
      <month>9</month>
      <day>5</day>
      <hour>0</hour>
      <minute>0</minute>
      <second>0</second>
    </stop>
    <mode>DEVELOPMENT</mode>
    <descr>none4</descr>
  </item>
  <item>
    <start>
      <year>2021</year>
      <month>9</month>
      <day>5</day>
      <hour>10</hour>
      <minute>17</minute>
      <second>31</second>
    </start>
    <stop>
      <year>2021</year>
      <month>9</month>
      <day>5</day>
      <hour>13</hour>
      <minute>17</minute>
      <second>31</second>
    </stop>
    <mode>RELAXATION</mode>
    <descr>none5</descr>
  </item>
  <item>
    <start>
      <year>2021</year>
      <month>9</month>
      <day>6</day>
      <hour>23</hour>
      <minute>59</minute>
      <second>59</second>
    </start>
    <stop>
      <year>2021</year>
      <month>9</month>
      <day>7</day>
      <hour>0</hour>
      <minute>0</minute>
      <second>0</second>
    </stop>
    <mode>RELAXATION</mode>
    <descr>none6</descr>
  </item>
  <item>
    <start>
      <year>2021</year>
      <month>9</month>
      <day>7</day>
      <hour>0</hour>
      <minute>0</minute>
      <second>0</second>
    </start>
    <stop>
      <year>2021</year>
      <month>9</month>
      <day>7</day>
      <hour>2</hour>
      <minute>53</minute>
      <second>18</second>
    </stop>
    <mode>RELAXATION</mode>
    <descr>none6</descr>
  </item>
  <item>
    <start>
      <year>2021</year>
      <month>9</month>
      <day>7</day>
      <hour>23</hour>
      <minute>59</minute>
      <second>59</second>
    </start>
    <stop>
      <year>2021</year>
      <month>9</month>
      <day>8</day>
      <hour>0</hour>
      <minute>0</minute>
      <second>0</second>
    </stop>
    <mode>DEVELOPMENT</mode>
    <descr>none7</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>9</hour>
      <minute>8</minute>
      <second>21</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>9</hour>
      <minute>8</minute>
      <second>24</second>
    </stop>
    <mode>DEVELOPMENT</mode>
    <descr>Some reading</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>9</hour>
      <minute>9</minute>
      <second>0</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>9</hour>
      <minute>9</minute>
      <second>2</second>
    </stop>
    <mode>STAGNATION</mode>
    <descr>yo</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>12</hour>
      <minute>13</minute>
      <second>34</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>12</hour>
      <minute>13</minute>
      <second>44</second>
    </stop>
    <mode>STAGNATION</mode>
    <descr>none</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>12</hour>
      <minute>13</minute>
      <second>59</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>12</hour>
      <minute>14</minute>
      <second>1</second>
    </stop>
    <mode>RELAXATION</mode>
    <descr>none</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>12</hour>
      <minute>14</minute>
      <second>4</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>12</hour>
      <minute>14</minute>
      <second>7</second>
    </stop>
    <mode>DEVELOPMENT</mode>
    <descr>none</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>12</hour>
      <minute>55</minute>
      <second>56</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>12</hour>
      <minute>55</minute>
      <second>57</second>
    </stop>
    <mode>STAGNATION</mode>
    <descr>yo wow some cool things</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>13</hour>
      <minute>16</minute>
      <second>17</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>13</hour>
      <minute>16</minute>
      <second>19</second>
    </stop>
    <mode>STAGNATION</mode>
    <descr>Very long descripption is here..</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>19</minute>
      <second>53</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>35</minute>
      <second>23</second>
    </stop>
    <mode>STAGNATION</mode>
    <descr>none</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>35</minute>
      <second>29</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>39</minute>
      <second>35</second>
    </stop>
    <mode>DEVELOPMENT</mode>
    <descr>wow</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>45</minute>
      <second>43</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>45</minute>
      <second>45</second>
    </stop>
    <mode>STAGNATION</mode>
    <descr>wow</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>49</minute>
      <second>36</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>54</minute>
      <second>49</second>
    </stop>
    <mode>DEVELOPMENT</mode>
    <descr>wow</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>55</minute>
      <second>29</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>56</minute>
      <second>1</second>
    </stop>
    <mode>DEVELOPMENT</mode>
    <descr>to test</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>56</minute>
      <second>6</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>56</minute>
      <second>9</second>
    </stop>
    <mode>STAGNATION</mode>
    <descr>to test</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>56</minute>
      <second>20</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>56</minute>
      <second>22</second>
    </stop>
    <mode>STAGNATION</mode>
    <descr>to test</descr>
  </item>
  <item>
    <start>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
      <hour>16</hour>
      <minute>57</minute>
      <second>40</second>
    </start>
    <stop>
      <year>2022</year>
      <month>9</month>
      <day>4</day>
